apiVersion: v1
kind: Pod
metadata:
  name: shedding
  namespace: adhoc
spec:
  containers:
    - name: shedding
      image: registry-vpc.cn-hangzhou.aliyuncs.com/xapp/shedding:v1
      imagePullPolicy: Always
      resources:
        requests:
          cpu: 1000m
        limits:
          cpu: 1000m
  imagePullSecrets:
    - name: aliyun
