apiVersion: v1
kind: Pod
metadata:
  name: etcdmon
  namespace: discov
spec:
  containers:
  - name: etcdmon
    image: registry-vpc.cn-hangzhou.aliyuncs.com/xapp/etcdmon:v200620093045
    imagePullPolicy: Always
    env:
    - name: ETCD_CLUSTER
      value: etcd.discov:2379
  imagePullSecrets:
  - name: aliyun
