apiVersion: apps/v1
kind: Deployment
metadata:
  name: unaryserver-deployment
  namespace: adhoc
  labels:
    app: unaryserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: unaryserver
  template:
    metadata:
      labels:
        app: unaryserver
    spec:
      containers:
      - name: unaryserver
        image: registry-vpc.cn-hangzhou.aliyuncs.com/xapp/unaryserver:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3456
      imagePullSecrets:
        - name: aliyun
