apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sub
  name: sub
  namespace: adhoc
spec:
  containers:
    - command:
        - /app/sub
      image: registry-vpc.cn-hangzhou.aliyuncs.com/xapp/sub:v200213220509
      name: sub
  imagePullSecrets:
    - name: aliyun
  restartPolicy: Always
