apiVersion: v1
kind: Service
metadata:
  name: graceful
  namespace: kevin
spec:
  selector:
    app: graceful
  type: ClusterIP
  ports:
    - name: graceful-port
      port: 3333
      targetPort: 8888

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: graceful-deployment
  namespace: kevin
  labels:
    app: graceful
spec:
  replicas: 3
  selector:
    matchLabels:
      app: graceful
  template:
    metadata:
      labels:
        app: graceful
    spec:
      containers:
        - name: graceful
          image: registry-vpc.cn-hangzhou.aliyuncs.com/xapp/graceful:v191031145905
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
      imagePullSecrets:
        - name: aliyun

