apiVersion: apps/v1
kind: Deployment
metadata:
  name: gracefulrpc-deployment
  namespace: kevin
  labels:
    app: gracefulrpc
spec:
  replicas: 9
  selector:
    matchLabels:
      app: gracefulrpc
  template:
    metadata:
      labels:
        app: gracefulrpc
    spec:
      containers:
        - name: gracefulrpc
          image: registry-vpc.cn-hangzhou.aliyuncs.com/xapp/gracefulrpc:v191031144304
          imagePullPolicy: Always
          ports:
            - containerPort: 3456
      imagePullSecrets:
        - name: aliyun
