apiVersion: v1
kind: Service
metadata:
  name: unaryproxy
  namespace: kevin
spec:
  selector:
    app: unaryproxy
  ports:
    - name: unaryproxy-port
      port: 3456

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: unaryproxy-deployment
  namespace: kevin
  labels:
    app: unaryproxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: unaryproxy
  template:
    metadata:
      labels:
        app: unaryproxy
    spec:
      containers:
        - name: unaryproxy
          image: registry-vpc.cn-hangzhou.aliyuncs.com/xapp/unaryproxy:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3456
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime
      imagePullSecrets:
        - name: aliyun
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
