apiVersion: apps/v1
kind: Deployment
metadata:
  name: pub-deployment
  namespace: adhoc
  labels:
    app: pub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pub
  template:
    metadata:
      labels:
        app: pub
    spec:
      containers:
      - name: pub
        image: registry-vpc.cn-hangzhou.aliyuncs.com/xapp/pub:v200213172101
        command:
        - /app/pub
        - -v
        - ccc
      imagePullSecrets:
      - name: aliyun
