apiVersion: apps/v1
kind: Deployment
metadata:
  name: unarydirect-deployment
  namespace: adhoc
  labels:
    app: unarydirect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unarydirect
  template:
    metadata:
      labels:
        app: unarydirect
    spec:
      containers:
        - name: unarydirect
          image: registry-vpc.cn-hangzhou.aliyuncs.com/xapp/unarydirect:v1
          imagePullPolicy: Always
      imagePullSecrets:
        - name: aliyun
